const actions = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  GET_SELECTED_PRODUCT: 'GET_SELECTED_PRODUCT',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
};

export default actions;
